version: '2.1'
services:
  web:
    build:
      context: ./
      dockerfile: ./docker-release/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:80'
    command:
      - nginx
      - -g
      - daemon off;
