version: 2

defaults:
    working_directory: ~/repo

jobs:
  build:
    # Run tests inside a docker container set up on CircleCI
    docker:
      - image: circleci/node:11.6.0

    # Steps to run tests
    steps:
      # Checkout the code
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install the node modules
          command: yarn install

      # Save node_modules to cache to speed up subsequent builds
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      # run tests!
      - run: # run tests
          name: Run the tests and report coverage
          command: |
            yarn test:unit

      # upload code coverage
      - run:
          name: Send coverage to CodeCov
          command: yarn add --dev codecov && ./node_modules/.bin/codecov
